In [1]:
import numpy as np

In [2]:
#Creating a 1D numpy array

arr = np.array([1,2,3,4,5])

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
#Creating a 2D array

arr1 = np.array( [  [1,2,3],
                   [4,5,6] ] )

In [5]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# Creating array of ones

np.ones(5) #1D 
np.ones( (3,5) ) #2D

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
# Change the default dtype of an array 

np.ones( (5) ,dtype = np.int) # creating array of integers
np.ones( (5) ,dtype = np.float ) # creating array of floats

array([1., 1., 1., 1., 1.])

In [8]:
# Creating array of random numbers

np.random.random( [3,4] ) 

array([[0.68790507, 0.04888056, 0.75605524, 0.43678925],
       [0.88413448, 0.04210945, 0.09692177, 0.75024541],
       [0.51934478, 0.32349816, 0.89095731, 0.684984  ]])

In [9]:
np.random.random(10)

array([0.51937861, 0.22600323, 0.10192588, 0.8156009 , 0.78950632,
       0.78894305, 0.84248459, 0.14634444, 0.09728959, 0.11472715])

In [10]:
#creating an array of numbers 1 to 100 with step of 5

np.arange(1,100,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [11]:
#Creating an array of length 25 between 1 to 10

np.linspace(1,10,25)  # It equally divides 1 to 100 in 25 parts

array([ 1.   ,  1.375,  1.75 ,  2.125,  2.5  ,  2.875,  3.25 ,  3.625,
        4.   ,  4.375,  4.75 ,  5.125,  5.5  ,  5.875,  6.25 ,  6.625,
        7.   ,  7.375,  7.75 ,  8.125,  8.5  ,  8.875,  9.25 ,  9.625,
       10.   ])

In [12]:
#creating a array of particular number

np.full( ( 3,3) , 5) #It will create an array of 3x3 of 5's

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [13]:
# To create an array of repeating sequence

np.tile( [1,2,3] , 3 ) # The op will look like [ 1,2,3,1,2,3,1,2,3 ]

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [14]:
# Creating an array of identity matrix

np.eye(3, dtype = int )   # it will create an 3x3 identity matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [15]:
#create a matrix of random integer between a particular range

np.random.randint(0, 10, (3,3))  #3x3 array of random integers ranging from 0 to 9

array([[0, 6, 0],
       [4, 2, 9],
       [9, 8, 5]])

In [16]:
# creating uninitialized array of specific shape and dtype

np.empty( [3,3] , dtype = int ) 

array([[         4,         32,          4],
       [        36,         23,  543520108],
       [-959105856,        576,          1]])

In [20]:
#create an array of specific shape filled with zeroes


np.zeros( [10,3] , dtype = int )

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [24]:
# Checking shape of an array

arr = np.array( [1,2,3] )
arr.shape

(3,)

In [25]:
#checking dimensions of an array


arr.ndim

1

In [26]:
arr.size  #checking shape of an array

3

In [27]:
arr1.size #checking shape of an array

6

In [29]:
#checking the dtype of an array

np.dtype

numpy.dtype

In [30]:
arr = np.array( [1,2,3,4,5,6,7,8,9] ) 

In [31]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr.reshape( [3,3]) # convering above array in 3x3 matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
#flatenning the array

y = np.array( [[1,1], [1,1] ])
y.flatten()  # output : [1,1,1,1]

array([1, 1, 1, 1])

In [41]:
array_1d= np.array([11,22,33,44,55,66,77,88,99,123,121,456,789,253,3654,7,5,6,9,12,58,98,36,97,99,54,56,25,36,78])



In [43]:
array_1d

array([  11,   22,   33,   44,   55,   66,   77,   88,   99,  123,  121,
        456,  789,  253, 3654,    7,    5,    6,    9,   12,   58,   98,
         36,   97,   99,   54,   56,   25,   36,   78])

In [42]:
array_1d[2] # Third element 
array_1d[2:] # Third element onwards 
array_1d[:3] # First three elements 
array_1d[2:7] # Third to seventh elements 
array_1d[0::2] # Subset starting 0 at increment of 2

array([  11,   33,   55,   77,   99,  121,  789, 3654,    5,    9,   58,
         36,   99,   56,   36])

In [44]:
array_1d[2] # Third element 

33

In [45]:
array_1d[2:] # Third element onwards 

array([  33,   44,   55,   66,   77,   88,   99,  123,  121,  456,  789,
        253, 3654,    7,    5,    6,    9,   12,   58,   98,   36,   97,
         99,   54,   56,   25,   36,   78])

In [46]:
array_1d[:3] # First three elements 

array([11, 22, 33])

In [47]:
array_1d[2:7] # Third to seventh elements 

array([33, 44, 55, 66, 77])

In [48]:
array_1d[0::2] # Subset starting 0 at increment of 2

array([  11,   33,   55,   77,   99,  121,  789, 3654,    5,    9,   58,
         36,   99,   56,   36])

In [49]:
print(arr[0]) #it will print first row 

1


In [50]:
print(arr[1]) #it will print second row 

2


In [52]:
#Concatenating 1D array

arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)

#output : [1 2 3 4 5 6]

[1 2 3 4 5 6]


In [53]:
#Concatenating @d array along axis 0
arr1=np.array([[1,1,1],[1,1,1]])
arr2=np.array([[9,9,9,],[9,9,9]])
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)


[[1 1 1]
 [1 1 1]
 [9 9 9]
 [9 9 9]]


In [54]:
#concatenating along axsi 1
arr1=np.array([[1,1,1],[1,1,1]]) 
arr2=np.array([[9,9,9,],[9,9,9]]) 
arr=np.concatenate((arr1,arr2),axis=1) 
print(arr) 


[[1 1 1 9 9 9]
 [1 1 1 9 9 9]]


In [55]:
#stacking two 1D arrays horizontally

arr1=np.array([0,0]) 
arr2=np.array([1,1])
arr=np.hstack((arr1,arr2))

In [56]:
arr

array([0, 0, 1, 1])

In [57]:
# Stacking two 2D arrays horizontally
arr1=np.array([[0,0],[0,0]]) 
arr2=np.array([[1,1],[1,1]]) 
arr=np.hstack((arr1,arr2)) 
print(arr)

[[0 0 1 1]
 [0 0 1 1]]


In [59]:
#Stacking 1D arrays vertically
arr1=np.array([0,0]) 
arr2=np.array([1,1]) 
arr=np.vstack((arr1,arr2)) 
print(arr) 


[[0 0]
 [1 1]]


In [60]:
arr=np.array([3,2,0,1]) 
print(np.sort(arr))

[0 1 2 3]


In [61]:
np.array([0,1]) + np.array([2,3])

array([2, 4])

In [62]:
np.array([0,1]) * np.array([2,3])

array([0, 3])

In [63]:
np.array([0,1])**2 #squaring

array([0, 1], dtype=int32)

In [64]:
np.array([1,2]) ** 1.2 #raising power by 1.2

array([1.        , 2.29739671])

In [65]:
arr = np.array([1,2,3])

In [66]:
np.sin(arr)

array([0.84147098, 0.90929743, 0.14112001])

In [67]:
np.cos(arr)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [68]:
np.tan(arr)

array([ 1.55740772, -2.18503986, -0.14254654])

In [69]:
np.exp(arr)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [70]:
np.log( arr )

array([0.        , 0.69314718, 1.09861229])