In [3]:
import numpy as np 
ab = np.array([1,2,3]) 
ab

array([1, 2, 3])

In [5]:
a1 = np.array([[1, 2], [3, 4]]) 
a1

array([[1, 2],
       [3, 4]])

In [4]:
a=[1,2,3,4,5]
b=[4,5,6,7,8]

np.array(a)+np.array(b)

array([ 5,  7,  9, 11, 13])

In [6]:
np.array(a)+np.array(b)

b_arr=np.array([4,5,7,8])

np.square(b_arr)

array([16, 25, 49, 64], dtype=int32)

In [7]:
np.sum(b_arr)

24

In [8]:
import numpy as np

a_list=[1,2,3,4,5,6]
arr=np.array(a_list)

exp=np.array([[1,2,3,4,5,6],[4,5,6,7,8,9]])

In [9]:
exp.ndim #minimum dimensions

2

In [10]:
exp.shape #returns the shape of array

(2, 6)

In [17]:
exp.reshape

<function ndarray.reshape>

In [19]:
#Find the Eucledian distance b|w a & b

a=[1,2,3,4,5]
b=[4,1,3,7,9]

def educledian_dis(x,y):

    point1=np.array(x)
    point2=np.array(y)
    return np.sqrt(np.sum(np.square(point1-point2)))

educledian_dis(a,b)

5.916079783099616

In [22]:
p=np.array([1,2,3,4])
q=np.array([4,5,6,7])

np.dot(p,q)

p*q

array([ 4, 10, 18, 28])

In [23]:

np.dot(p,q)

60

In [24]:
#Reverse the string
arr=np.array([1,2,3,4,5,6])

arr[::-1]

array([6, 5, 4, 3, 2, 1])

In [26]:
#array Example
arr1=np.array([[1,2,3,4,5,6,7,8,9],[11,22,33,44,55,66,77,88,99]])

arr1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [11, 22, 33, 44, 55, 66, 77, 88, 99]])

In [27]:
#Shape
arr1.shape

(2, 9)

In [31]:
#Reshape
arr1.reshape(-1,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [32]:
arr1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [11, 22, 33, 44, 55, 66, 77, 88, 99]])

In [35]:
arr1[1][2] #indexing Elemeing of the Way

33

In [68]:
#To generate Some Random Number

arr1[1][2]

x=np.random.random((4,5))   

x

array([[0.19267763, 0.83500115, 0.72636269, 0.28538686, 0.03846566],
       [0.20595158, 0.10666137, 0.24192111, 0.93814144, 0.49179915],
       [0.97871428, 0.2807222 , 0.22709936, 0.81026544, 0.81227386],
       [0.1245983 , 0.04643114, 0.37934113, 0.15182245, 0.3943374 ]])

In [70]:
x.flatten()

x.flatten().shape

(20,)

In [79]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [80]:
np.amax(p) #returns Maximun Value in array
np.amin(p) #returns Minumin Value in array

1

In [ ]:
#WAPF that Takes Values & Returns the Values in any Shape





In [59]:
#Jaccard Similarity

user1=['Dark','waling Dead','zombie land','Inception','harry pottor']
user2=['Zombie land','Dark','goblin','Inception','Save Me','Come And Hug Me']

set(user1)


{'Dark', 'Inception', 'harry pottor', 'waling Dead', 'zombie land'}

In [50]:
set(user2)

{'Come And Hug Me', 'Dark', 'Inception', 'Save Me', 'Zombie land', 'goblin'}

In [54]:
un=set(user1).union(set(user2))
un

{'Come And Hug Me',
 'Dark',
 'Inception',
 'Save Me',
 'Zombie land',
 'goblin',
 'harry pottor',
 'waling Dead',
 'zombie land'}

In [55]:
it=set(user1).intersection(set(user2))
it

{'Dark', 'Inception'}

In [56]:
js=len(it)/len(un)
js

0.2222222222222222